AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  APIKeyQueryString blog post.
Globals:
  Function:
    Timeout: 10
  Api:
    OpenApiVersion: 3.0.1


Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth_function/
      Handler: app.lambda_handler
      Runtime: python3.8
  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: short_funnel/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        health:
          Type: Api
          Properties:
            RestApiId:
              Ref: ShortFunnelApi
            Path: /health
            Method: post
        energy:
          Type: Api
          Properties:
            RestApiId:
              Ref: ShortFunnelApi
            Path: /energy
            Method: post

  ShortFunnelApi:
      DependsOn: AuthFunction
      Type: AWS::Serverless::Api
      Properties:
        StageName: dev
        EndpointConfiguration:
          Type: REGIONAL
        Auth:
            DefaultAuthorizer: LambdaRequestAuthorizer
            ApiKeyRequired: true
            Authorizers:
              LambdaRequestAuthorizer:
                FunctionPayloadType: REQUEST
                FunctionArn: !GetAtt AuthFunction.Arn
                Identity:
                  ReauthorizeEvery: 0
                  QueryStrings:
                    - apiKey
        DefinitionUri: swagger/v1.json

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn: MyApidevStage
    Properties:
      Name: !Join ["", [{"Ref": "AWS::StackName"}, "-apikey"]]
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ShortFunnelApi
          StageName: dev
      Value: !Join ["", [{"Ref": "AWS::StackName"}, "-abcdefhijk1234567890"]]

  UsagePlan:
    DependsOn: MyApidevStage
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref ShortFunnelApi
          Stage: dev
      Throttle:
        BurstLimit: 50
        RateLimit: 100
      UsagePlanName: MyUsagePlan

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for dev stage for api key validation in query string"
    Value: !Sub "https://${ShortFunnelApi}.execute-api.${AWS::Region}.amazonaws.com/dev/auth?apiKey=${AWS::StackName}-abcdefhijk1234567890"

