service: api-key-in-query-string-sls
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs14.x
  timeout: 30
  apiGateway:
    apiKeys:
      - value: ${opt:stage}-unbounce-sls-api-key
        description: Api key description # Optional
    usagePlan:
      quota:
        limit: 5000
        offset: 2
        period: MONTH
      throttle:
        burstLimit: 200
        rateLimit: 100

functions:
  MyAuthFunction:
    description: Extracts api key, authenticates against usage plan, allow/deny http methods and returns auth response object
    handler: ./auth.lambda_handler

  BackendFunction:
    handler: ./backend.lambda_handler
    runtime: nodejs14.x
    events:
      - http:
          method: post
          cors: true
          path: /shortfunnel-health
          authorizer:
            name: MyAuthFunction
            type: request
            authorizerId:
              Ref: ApiGatewayAuthorizer

resources:
  Resources:
    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        AuthorizerResultTtlInSeconds: 300
        IdentitySource: method.request.querystring.apiKey
        Name: Authorizer
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: REQUEST
        AuthorizerUri:
          Fn::Join: [ "",
            [
              "arn:aws:apigateway:",
              "ap-southeast-2",
              ":lambda:path/",
              "2015-03-31/functions/", "arn:aws:lambda:ap-southeast-2:327303463717:function:lambda_request_authorizer2",
              "/invocations"
            ]]

    GWAuthPermissions:
      Type: "AWS::Lambda::Permission"
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: "arn:aws:lambda:ap-southeast-2:327303463717:function:lambda_request_authorizer2"
        Principal: "apigateway.amazonaws.com"

  Outputs:
    MyApiHealth:
      Description: "API Gateway endpoint URL for dev stage for api key validation in query string"
      Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${opt:stage}/shortfunnel-health?apiKey=${opt:stage}-unbounce-api-key"
