version: 0.2

env:
  shell: bash
  variables:

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - source ./scripts/nvm_setup.sh
  pre_build:
    on-failure: ABORT
    commands:

  build:
    on-failure: ABORT
    commands:

  post_build:
    commands:
      - echo "build completed successfully."
